'on':
    release:
        types: [published]
    workflow_dispatch: {}

name: Release
jobs:
    release:
        permissions:
            contents: write
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      target: linux-x64
                      platformName: linux
                    - os: macos-latest
                      target: darwin-x64 darwin-arm64
                      platformName: mac
                    - os: windows-latest
                      target: win32-x64
                      platformName: win

        env:
            EXTENSION_FILE: renpy-warp-${{ github.ref_name }}-${{ matrix.platformName }}.vsix

        runs-on: '${{ matrix.os }}'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x

            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - run: npm install

            - name: create extension package
              run: >-
                  npm run package --
                  --out ${{ env.EXTENSION_FILE }}

            - name: create github release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: '*.vsix'
                  replacesArtifacts: false
                  tag: ${{ github.ref_name }}
                  allowUpdates: true
                  makeLatest: false
                  omitNameDuringUpdate: true
                  omitBodyDuringUpdate: true
                  omitPrereleaseDuringUpdate: true
                  omitDraftDuringUpdate: true

            - name: publish to open vsx registry
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  target: ${{ matrix.target }}
                  extensionFile: ${{ env.EXTENSION_FILE }}
                  registryUrl: https://open-vsx.org
                  pat: ${{ secrets.OVSX_TOKEN }}

            - name: publish to visual studio marketplace
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  target: ${{ matrix.target }}
                  extensionFile: ${{ env.EXTENSION_FILE }}
                  registryUrl: https://marketplace.visualstudio.com
                  pat: ${{ secrets.VSCE_PAT }}
